---
# tasks file for server

- name: Atualiza apt cache
  apt: update_cache=yes cache_valid_time=3600
  become: yes

- name: Instalar pacotes do servidor
  apt: name={{ item }} state=present
  become: yes
  with_items:
    - apache2
    - mysql-server
    - php8.1-mysql
    - php8.1
    - libapache2-mod-php8.1
    - python3-pymysql
